### PR TITLE
Add test cases as start of conversion process

### PR DESCRIPTION
**Pull request by bennahugo**
And so the pain starts....

### CODE REVIEW

**Comment by bennahugo** [comment]
@o-smirnov this can be merged

**Comment by bennahugo** [comment]
@o-smirnov do you have any objections to me changing the backend bindings to pybind11. The extension module system has changed substantially in python 3. I've managed to get it compiling against python 3's headers, but it now segfaults on import, so I'm guessing somewhere there is a py_decref that is called that shouldn't be.

**Comment by o-smirnov** [comment]
Oooh. Now that's going to be a mission and a half. Or more like, two dozen missions... Let's investigate the segfault a little first to see if we can fix it with less effort...

**Comment by bennahugo** [comment]
Still scratching my head on this. Managed to get gdb attached through python3. Somehow there is a double free error coming about.

**Comment by bennahugo** [comment]
Nvm... tracked it down.

**Comment by o-smirnov** [comment]
Ah good job! So no need for a pybind11 upheaval just yet?

**Comment by bennahugo** [comment]
Not yet :) steadily working my way back up through python land...

**Comment by bennahugo** [comment]
@o-smirnov ok with these chages the  gui opens up but as soon as I try and start the meqserver it crashes:
```
meqbrowser.py: Fatal IO error: client killed
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
```

Looks like it is a change in the way X handles a threaded application. Have you seen it before?

**Comment by o-smirnov** [comment]
Never. :(

**Comment by bennahugo** [comment]
Another issue I'm running into is that qwt5 is no longer maintained and has no python3 package

**Comment by bennahugo** [comment]
so the plotting extensions are all falling over:
```
 WARNING: couldn't import plugin 'Timba.Plugins.quickref_plotter' (No module named 'PyQt4.Qwt5')
  This plugin will not be available.

 WARNING: couldn't import plugin 'Timba.Plugins.collections_plotter' (No module named 'PyQt4.Qwt5')
  This plugin will not be available.

 WARNING: couldn't import plugin 'Timba.Plugins.array_plotter' (No module named 'QwtSpy_qt4')
  This plugin will not be available.

 WARNING: couldn't import plugin 'Timba.Plugins.result_plotter' (No module named 'QwtSpy_qt4')
```

**Comment by twillis449** [comment]
@bennahugo GAWD I admire you for attempting this exercise! As you point out PyQwt went poof a while ago and won't be ported to python 3. However have a look at  https://github.com/PierreRaybaut/PythonQwt  This individual rewrote a lot of the PyQwt stuff in pure python so one might be able to replace most of the PyQwt stuff with pure python equivalents.

**Comment by gijzelaerr** [comment]
PyQwt is missing a couple of widgets which are used by Tigger.  Recreating these widgets is probably not very trivial.

**Comment by twillis449** [comment]
The original complete PyQwt 5.2 C++ source code and sip wrappers is still available from sourceforge (pyqwt.sourceforge.net). It might or might not be a lot of work to upgrade the code to work with python 3 etc.

**Comment by bennahugo** [comment]
Yea I realized this only midway into this @twillis449. I've already tried the pure python libraries, there are missing diagnostic plots unfortunately (so not only Tigger is affected but the gui bit is affected too). Until we can get pyqwt ported I guess we'll be relying on Docker to keep our python 2 projects going well beyond 2020

**Comment by twillis449** [comment]
I just successfully built the above mentioned PyQwt 5.2 from scratch with Qt 4 and current sip. I have no idea how much work would be to adapt to Qt 5 and python 3,  but it might not be that difficult. I had a bit of a discussion with @o-smirnov a couple of years ago about replacing PyQwt with something like PyQtGraph but I don't think that would be worthwhile unless there was demand for a whole bunch of new visualization  displays.

**Comment by bennahugo** [comment]
Manually tested on python 3 and automated py2 tests passes (although the travis test may no longer work because we need to build against casacore version 3.1.1 and it takes too long to build).  This seems to work @twillis449 @o-smirnov can you please review

**Comment by bennahugo** [comment]
I'm going to switch the testing to our Jenkins server

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
No problem @twillis449. I'm trying to track down one last bug in tiling logic (i think it is in there). Once I'm sure the  predict is correct I will merge this and set up a python 3 CI test

**Comment by bennahugo** [comment]
nvm I was staring at auto correlations which are not predicted by the current codebase. We can merge this if there isn't any further change requests

**Pull request merged**
