### PR TITLE
Native qdbm issue1

### PR DESCRIPTION
**Pull request by o-smirnov**
This should solve the qdbm compilation issue (caused by missing hovel.h in recent qdbm packages).

### CODE REVIEW

**Comment by o-smirnov** [comment]
@gijzelaerr what's this Travis failure?

**Comment by gijzelaerr** [comment]
i'll have a look

**Comment by gijzelaerr** [comment]
So there are 2 failures. On build is the build of our branch directly, the second is a build of master as if this PR would have been merged. First one failed since you committed your changes on a checkout from more than 2 years ago, in the meanwhile the `.travis.yml` was updated by me to solve this issue.

The second build fails, since it looks like the requirements changed? the error is:
`Could NOT find DBM (missing: DBM_LIBRARIES DBM_INCLUDE_DIR)`

The travis file installs `libgdbm-dev` but you switched to QDBM?

**Comment by o-smirnov** [comment]
Yeah I was using qdbm in the past, but then it became incompatible with some Ubuntu (because qdbm dropped some legacy support). We therefore went back to gdbm for the standard package, and opened this branch to add native qdbm support again. Which has been done.

**Comment by o-smirnov** [comment]
For the first issue, let me merge master into this branch first.

**Comment by gijzelaerr** [comment]
ok cool, so probably just changing `libgdbm-dev` into `libqdbm-dev` in `.travis.yml` should solve the problem.

**Comment by gijzelaerr** [comment]
by the way, you can do this now also in the browser.

**Pull request merged**
