### PR TITLE
Fix for blitz 0.10 compatibility

### PR DESCRIPTION
**Pull request by Error323**
- This code was not tested, just compile error fixes.
 - The blitz interfaces for arrays have changed quite a bit.
 - Please check DMI/src/NumArrayFuncs3.cc for correctness.

### CODE REVIEW

**Comment by o-smirnov** [comment]
Yeah this can't be correct -- it needs both ```stride``` and ```blitz::neverdeleteData```. Have you found their equivalents in the new interfaces?

**Comment by Error323** [comment]
Indeed. I found them looking in the header defs as  my IDE parser didn't pick them up. Anyway I'll fix it asap.

**Comment by Error323** [comment]
Perhaps the buildsystem doesn't use blitz 0.10 yet. Please verify.

**Comment by gijzelaerr** [comment]
hm, travis-ci doesn't support ubuntu 14.04 yet. I'm just going to merge this and maybe switch to an other online test runner, but not now.

**Pull request merged**
